### ISSUE TITLE
cannot clone github-for-everyone

### ISSUE THREAD

**Issue by kkvls2004** [githubschool/github-for-everyone#59]
I can't seem to navigate to this repo to clone it on Github Desktop.  My preferences did log in successfully using this ID so I'm not sure what's wrong.

**Comment by jaw6** [comment]
@kkvls2004 what happens when you click the `Clone in Desktop` button from the front page of this repository?

![githubschool_github-for-everyone](https://cloud.githubusercontent.com/assets/2077/11072664/71158196-87ac-11e5-9799-b60bc8a51493.jpg)

**Comment by kkvls2004** [comment]
That worked!  Thank you!
